services:
  db:
    image: postgres:17-alpine
    container_name: authentik-db-${ENV_TAG}

    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTHENTIK_DB_NAME}
      POSTGRES_USER: ${AUTHENTIK_DB_USER}
      POSTGRES_PASSWORD: ${AUTHENTIK_DB_PASSWORD}
      INVENTORY_DB_NAME: ${INVENTORY_DB_NAME}
      INVENTORY_DB_USER: ${INVENTORY_DB_USER}
      INVENTORY_DB_PASSWORD: ${INVENTORY_DB_PASSWORD}

    volumes:
      - /system_config/postgres/init-app-db.sh:/docker-entrypoint-initdb.d/init-app-db.sh:ro
      - /system_config/postgres/data:/var/lib/postgresql/data
      - /system_config/olivetin/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data:
